#!/usr/bin/env python3
"""
Digest Generator: Creates a Jupyter notebook summarizing recent papers.

Usage:
    python research_tracker/digest.py [--days N] [--min-score N]
"""

import argparse
import json
import nbformat
from datetime import datetime, timedelta
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).parent
PROJECT_DIR = SCRIPT_DIR.parent
CONFIG_PATH = SCRIPT_DIR / "config.yaml"


def load_config() -> dict:
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def load_papers_db() -> dict:
    config = load_config()
    db_path = PROJECT_DIR / config["output"]["papers_db"]
    if db_path.exists():
        with open(db_path) as f:
            return json.load(f)
    return {"papers": {}}


def create_digest_notebook(days: int = 30, min_score: int = 2) -> str:
    """Create a digest notebook from recent papers."""
    config = load_config()
    db = load_papers_db()
    notebook_mapping = config.get("notebook_mapping", {})

    cutoff = (datetime.now() - timedelta(days=days)).isoformat()

    # Filter recent, relevant papers
    recent_papers = []
    for pid, paper in db["papers"].items():
        added = paper.get("added_date", paper.get("date", ""))
        score = paper.get("relevance_score", 0)
        if added >= cutoff and score >= min_score:
            recent_papers.append(paper)

    # Sort by relevance score
    recent_papers.sort(key=lambda p: p.get("relevance_score", 0), reverse=True)

    if not recent_papers:
        print("No papers found matching criteria.")
        return ""

    # Group by category
    categorized = {}
    for paper in recent_papers:
        for cat in paper.get("categories", ["General"]):
            categorized.setdefault(cat, []).append(paper)

    # Create notebook
    nb = nbformat.v4.new_notebook()
    nb.metadata["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }

    # Title cell
    date_str = datetime.now().strftime("%Y-%m-%d")
    title_md = f"""# Research Digest: {date_str}

**Papers found:** {len(recent_papers)} (from last {days} days, relevance >= {min_score})

*Auto-generated by the research tracker. See `research_tracker/config.yaml` to customize.*

---"""
    nb.cells.append(nbformat.v4.new_markdown_cell(title_md))

    # Summary table
    table_md = "## Overview\n\n"
    table_md += "| Score | Title | Categories | Date |\n"
    table_md += "|-------|-------|------------|------|\n"
    for paper in recent_papers[:20]:  # Top 20
        cats = ", ".join(paper.get("categories", []))
        title = paper["title"][:70] + ("..." if len(paper["title"]) > 70 else "")
        url = paper.get("url", "")
        score = paper.get("relevance_score", 0)
        date = paper.get("date", "")[:10]
        table_md += f"| {score} | [{title}]({url}) | {cats} | {date} |\n"
    nb.cells.append(nbformat.v4.new_markdown_cell(table_md))

    # Category sections
    for category in sorted(categorized.keys()):
        papers = categorized[category]
        related_nb = notebook_mapping.get(category, "")

        section_md = f"## {category}"
        if related_nb:
            section_md += f"\n*Related guide notebook: `{related_nb}`*"
        section_md += f"\n\n**{len(papers)} papers**\n"

        for paper in papers[:5]:  # Top 5 per category
            section_md += f"\n### [{paper['title']}]({paper.get('url', '')})\n"
            section_md += f"**Authors:** {', '.join(paper['authors'][:5])}"
            if len(paper["authors"]) > 5:
                section_md += f" et al."
            section_md += f"  \n"
            section_md += f"**Date:** {paper.get('date', 'N/A')[:10]} | "
            section_md += f"**Relevance:** {paper.get('relevance_score', 0)} | "
            section_md += f"**Keywords:** {', '.join(paper.get('matched_keywords', [])[:5])}\n\n"

            # Truncated abstract
            abstract = paper.get("abstract", "")
            if len(abstract) > 500:
                abstract = abstract[:500] + "..."
            section_md += f"> {abstract}\n"

        nb.cells.append(nbformat.v4.new_markdown_cell(section_md))

    # Update suggestions section
    suggestions = generate_update_suggestions(recent_papers, config)
    if suggestions:
        suggestions_md = "## Suggested Guide Updates\n\n"
        suggestions_md += "Based on new papers, here are suggested updates to the study guide:\n\n"

        # Group by notebook
        by_notebook = {}
        for s in suggestions:
            by_notebook.setdefault(s["notebook"], []).append(s)

        for notebook in sorted(by_notebook.keys()):
            suggestions_md += f"### `{notebook}`\n"
            for s in by_notebook[notebook][:3]:  # Top 3 per notebook
                suggestions_md += f"- **[{s['suggestion_type'].upper()}]** {s['suggestion_text']}\n"
            suggestions_md += "\n"

        nb.cells.append(nbformat.v4.new_markdown_cell(suggestions_md))

    # Save
    digests_dir = PROJECT_DIR / config["output"]["digests_dir"]
    digests_dir.mkdir(parents=True, exist_ok=True)

    filename = f"digest_{date_str}.ipynb"
    output_path = digests_dir / filename

    with open(output_path, "w") as f:
        nbformat.write(nb, f)

    print(f"Digest saved to: {output_path}")
    print(f"Papers included: {len(recent_papers)}")
    print(f"Categories: {', '.join(sorted(categorized.keys()))}")

    return str(output_path)


def generate_update_suggestions(recent_papers, config):
    """Generate suggestions for updating guide notebooks based on new papers."""
    notebook_mapping = config.get("notebook_mapping", {})
    suggestions = []

    for paper in recent_papers:
        categories = paper.get("categories", [])
        score = paper.get("relevance_score", 0)

        if score < 5:
            continue  # Only suggest for relevant papers

        for cat in categories:
            notebook = notebook_mapping.get(cat, "")
            if notebook:
                suggestion = {
                    "notebook": notebook,
                    "paper_title": paper["title"],
                    "paper_url": paper.get("url", ""),
                    "category": cat,
                    "relevance_score": score,
                    "suggestion_type": classify_suggestion(paper, cat),
                    "suggestion_text": generate_suggestion_text(paper, cat, notebook),
                }
                suggestions.append(suggestion)

    return suggestions


def classify_suggestion(paper, category):
    """Classify what kind of update this paper suggests."""
    title_lower = paper["title"].lower()
    abstract_lower = paper.get("abstract", "").lower()
    text = f"{title_lower} {abstract_lower}"

    if any(w in text for w in ["survey", "review", "overview", "tutorial"]):
        return "add_reference"
    elif any(w in text for w in ["new method", "novel", "introduce", "propose"]):
        return "new_technique"
    elif any(w in text for w in ["scaling", "larger model", "frontier"]):
        return "update_scaling"
    elif any(w in text for w in ["benchmark", "evaluation", "comparison"]):
        return "update_evaluation"
    else:
        return "add_reference"


def generate_suggestion_text(paper, category, notebook):
    """Generate human-readable suggestion for updating a notebook."""
    suggestion_type = classify_suggestion(paper, category)
    title = paper["title"]
    url = paper.get("url", "")

    templates = {
        "new_technique": f"NEW TECHNIQUE: '{title}' introduces a new approach relevant to this notebook. Consider adding a section or subsection describing this method. [{url}]",
        "update_scaling": f"SCALING UPDATE: '{title}' extends techniques to larger models. Update the notebook's discussion of scalability. [{url}]",
        "update_evaluation": f"EVALUATION: '{title}' provides new benchmarks/comparisons. Consider updating evaluation metrics or adding to the evaluation section. [{url}]",
        "add_reference": f"NEW REFERENCE: Add '{title}' to the Further Reading section. [{url}]",
    }

    return templates.get(suggestion_type, templates["add_reference"])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate research digest notebook")
    parser.add_argument("--days", type=int, default=30, help="Days to include")
    parser.add_argument("--min-score", type=int, default=2, help="Minimum relevance score")
    args = parser.parse_args()

    create_digest_notebook(days=args.days, min_score=args.min_score)
